export const turbo = [
  {
    _id: "66df67d373fc8b871a9f3220",
    aircraftName: "King Air F90",
    registration: "N30GT",
    seats: "6",
    lavatory: "Yes",
    altitude: "24,000'",
    cabinHeight: "4'10",
    cabinLength: "12'",
    cabinWidth: "4'6\"",
    description: "This is a good plain",
    doorHeight: "4'3\"",
    doorWidth: "2'3\"",
    luggageCapacity: "54 cu. ft",
    range: "1400NM",
    speed: "300KTAS",
    wifi: "N/A",
    amenities:
      "Custom Leather Upholstery,Power outlets,Luggage Racks and Hangars,Galley area,Chiller, Aft lavatory with full vanity",
    category: "TURBOPROPS",
    yom: "YOR 2022",
    imageUrls: [
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N30GT/exterior.jpg?...",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N30GT/interior/1.jpg?...",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N30GT/others/30GT_configuration.jpg?...",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N30GT/others/CSM_N30GT_fleetsheet.pdf?...",
    ],
  },
  {
    _id: "66df6a1473fc8b871a9f3222",
    aircraftName: "King Air 200",
    registration: "N923AS",
    seats: "7+1",
    lavatory: "Yes",
    altitude: "24,000'",
    cabinHeight: "4'10",
    cabinLength: "16'8\"",
    cabinWidth: "4'6\"",
    description: "This is a very good plain",
    doorHeight: "4'3\"",
    doorWidth: "2'3\"",
    luggageCapacity: "54 cu. ft",
    range: "1450NM",
    speed: "300KTAS",
    wifi: "N/A",
    amenities:
      "Custom Leather Upholstery,Power outlets,Luggage Racks and Hangars,Galley area,Chiller, Aft lavatory with full vanity",
    category: "TURBOPROPS",
    yom: "YOR 2022",
    imageUrls: [
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N923AS/exterior.jpg?...",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N923AS/interior/923AS-interior.jpg?...",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N923AS/interior/snow.png?...",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N923AS/others/132N-config_jfif.jpg?...",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N923AS/others/CSM_Fleetsheet_N923AS.pdf?...",
    ],
  },
  {
    _id: "66eca9bad34a43dc8b431214",
    aircraftName: "King Air B200",
    registration: "N132N",
    seats: "7+1",
    lavatory: "Yes",
    altitude: "24,000'",
    cabinHeight: "4'10",
    cabinLength: "16'8\"",
    cabinWidth: "4'6\"",
    description: "This is a very good plain",
    doorHeight: "4'3\"",
    doorWidth: "2'3\"",
    luggageCapacity: "54 cu. ft",
    range: "1450NM",
    speed: "300KTAS",
    wifi: "N/A",
    amenities:
      "Custom Leather Upholstery,Power outlets,Luggage Racks and Hangars,Galley area,Chiller, Aft lavatory with full vanity",
    category: "TURBOPROPS",
    yom: "YOR 2022",
    imageUrls: [
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N132N/exterior.jpg?...",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N132N/interior/1.png?...",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N132N/interior/2.png?...",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N132N/others/132N-config_jfif.jpg?...",
    ],
  },
  {
    _id: "66ecab50d34a43dc8b431215",
    aircraftName: "King Air B200GT",
    registration: "N177TA",
    seats: "7",
    lavatory: "Yes",
    altitude: "24,000'",
    cabinHeight: "4'10",
    cabinLength: "16'8\"",
    cabinWidth: "4'6\"",
    description: "This is a very good plain",
    doorHeight: "4'3\"",
    doorWidth: "2'3\"",
    luggageCapacity: "54 cu. ft",
    range: "1450NM",
    speed: "300KTAS",
    wifi: "N/A",
    amenities:
      "Custom Leather Upholstery,Power outlets,Luggage Racks and Hangars,Galley area,Chiller, Aft lavatory with full vanity",
    category: "TURBOPROPS",
    yom: "YOM 2007 YOR 2022",
    imageUrls: [
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N177TA/exterior.jpg?...",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N177TA/interior/1.jpg?...",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N177TA/others/132N-config_jfif.jpg?...",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N177TA/others/CSM_Fleetsheet_N923AS.pdf?...",
    ],
  },
];

export const lightMidsizeAircraft = [
  {
    aircraftName: "Citation Bravo",
    registration: "N550ML",
    seats: "7",
    lavatory: "Yes",
    altitude: "43,000'",
    cabinHeight: "4'10\"",
    cabinLength: "15'8\"",
    cabinWidth: "4'6\"",
    description: "This is a very good plain",
    doorHeight: '4"',
    doorWidth: '2"',
    luggageCapacity: "73 cu. ft",
    range: "1980NM",
    speed: "410KTAS",
    wifi: "N/A",
    amenities:
      "Custom Leather Upholstery, Power outlets, Luggage Racks and Hangars, Galley area, Chiller, Aft lavatory with full vanity",
    category: "LIGHT | MIDSIZE JETS",
    yom: "YOM 2004 | YOR 2022",
    imageUrls: [
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N550ML/exterior.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N550ML/interior/550ML-interior.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N550ML/interior/550ML-interior2.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N550ML/interior/550ML.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N550ML/interior/550ML_1.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N550ML/others/Cessna-Citation-Bravo_2.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N550ML/others/N550ML_fleetsheet-compressed.pdf",
    ],
  },
  {
    aircraftName: "Gulfstream G150",
    registration: "N8821C",
    seats: "8+1",
    lavatory: "Yes",
    altitude: "45,000'",
    cabinHeight: "5'8\"",
    cabinLength: "17'8\"",
    cabinWidth: "5'8\"",
    description: "This is a very good plain",
    doorHeight: "",
    doorWidth: "",
    luggageCapacity: "80 cu. ft",
    range: "2760NM",
    speed: "470KTAS",
    wifi: "N/A",
    amenities:
      "Custom Leather Upholstery, Power outlets, Luggage Racks and Hangars, Galley area, Chiller, Aft lavatory with full vanity",
    category: "LIGHT | MIDSIZE JETS",
    yom: "YOM 2007 | YOR 2022",
    imageUrls: [
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N8821C/external.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N8821C/interior/8821C.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N8821C/interior/8821C_1.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N8821C/interior/8821C_2.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N8821C/interior/8821C_4.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N8821C/others/CSM_8821C_fleetsheet.pdf",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N8821C/others/N8821_Gulfstream_150-configuration.jpg",
    ],
  },
  {
    aircraftName: "Gulfstream G150",
    registration: "N518KH",
    seats: "8+1",
    lavatory: "Yes",
    altitude: "45,000'",
    cabinHeight: "5'8\"",
    cabinLength: "17'8\"",
    cabinWidth: "5'8\"",
    description: "This is a very good plain",
    doorHeight: "",
    doorWidth: "",
    luggageCapacity: "80 cu. ft",
    range: "2760NM",
    speed: "470KTAS",
    wifi: "N/A",
    amenities:
      "Custom Leather Upholstery, Power outlets, Luggage Racks and Hangars, Galley area, Chiller, Aft lavatory with full vanity",
    category: "LIGHT | MIDSIZE JETS",
    yom: "YOM 2007 | YOR 2022",
    imageUrls: [
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N518KH/exterior.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N518KH/others/CSM_518KH_fleet_sheet.pdf",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N518KH/others/N8821_Gulfstream_150-configuration.jpg",
    ],
  },
  {
    aircraftName: "Gulfstream G150",
    registration: "N360AV",
    seats: "7",
    lavatory: "Yes",
    altitude: "45,000'",
    cabinHeight: "5'8\"",
    cabinLength: "17'8\"",
    cabinWidth: "5'8\"",
    description: "This is a very good plain",
    doorHeight: "",
    doorWidth: "",
    luggageCapacity: "80 cu. ft",
    range: "2760NM",
    speed: "470KTAS",
    wifi: "N/A",
    amenities:
      "Custom Leather Upholstery, Power outlets, Luggage Racks and Hangars, Galley area, Chiller, Aft lavatory with full vanity",
    category: "LIGHT | MIDSIZE JETS",
    yom: "YOM 2008 | YOR 2022",
    imageUrls: [
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N360AV/exterior.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N360AV/interior/360AV_1.jpg",
      "https://s3.us-west-1.amazonaws.com/thisisatestspacefor.design/images/N360AV/interior/360AV_2.jpg",
    ],
  },
];
